version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester-uv
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            uv venv --python 3.9 /usr/local/share/virtualenvs/tap-selligent
            source /usr/local/share/virtualenvs/tap-selligent/bin/activate
            uv pip install .
      - run:
          name: 'pylint'
          command: |
            source /usr/local/share/virtualenvs/tap-selligent/bin/activate
            uv pip install pylint
            pylint tap_selligent --disable missing-docstring,logging-format-interpolation,no-member,broad-except,too-many-branches,dangerous-default-value,consider-using-f-string,missing-timeout,unused-argument,unspecified-encoding,raise-missing-from,consider-using-sys-exit

workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
